// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkPFzI4IGSS7WrggFApopPpM55UAiGfOI',
    appId: '1:1063438116773:web:70169cb4cdac3397876a4c',
    messagingSenderId: '1063438116773',
    projectId: 'nash-note',
    authDomain: 'nash-note.firebaseapp.com',
    storageBucket: 'nash-note.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcRiwbRJ_YiwRt2SzKdbElIo3tSaJ4s80',
    appId: '1:1063438116773:android:416377f1417f8782876a4c',
    messagingSenderId: '1063438116773',
    projectId: 'nash-note',
    storageBucket: 'nash-note.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANhvFXw67EnDbubGVhx86kMteFXlvbfwo',
    appId: '1:1063438116773:ios:422f11664b134569876a4c',
    messagingSenderId: '1063438116773',
    projectId: 'nash-note',
    storageBucket: 'nash-note.appspot.com',
    androidClientId: '1063438116773-v0tq7r7d5usbpgrn76ek1dk0bfbqfvbj.apps.googleusercontent.com',
    iosClientId: '1063438116773-07s86t5o2ct41rhl82ncjifn8d6j63o5.apps.googleusercontent.com',
    iosBundleId: 'com.example.nashNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANhvFXw67EnDbubGVhx86kMteFXlvbfwo',
    appId: '1:1063438116773:ios:422f11664b134569876a4c',
    messagingSenderId: '1063438116773',
    projectId: 'nash-note',
    storageBucket: 'nash-note.appspot.com',
    androidClientId: '1063438116773-v0tq7r7d5usbpgrn76ek1dk0bfbqfvbj.apps.googleusercontent.com',
    iosClientId: '1063438116773-07s86t5o2ct41rhl82ncjifn8d6j63o5.apps.googleusercontent.com',
    iosBundleId: 'com.example.nashNote',
  );
}
